export enum EActionPages {
  LOADING_DATA_PAGE = 'LOADING_DATA_PAGE',
  FAILURE_LOAD_DATA_PAGE = 'FAILURE_LOAD_DATA_PAGE',
  SUCCESS_DESTINATION_DATA_PAGE = 'SUCCESS_DESTINATION_DATA_PAGE',
  SUCCESS_CREW_DATA_PAGE = 'SUCCESS_CREW_DATA_PAGE',
  SUCCESS_TECHNOLOGY_DATA_PAGE = 'SUCCESS_TECHNOLOGY_DATA_PAGE',
}
