export enum ActionPages {
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  LOAD_DATA_PAGE = 'LOAD_DATA_PAGE',
  LOAD_DATA_PAGE_SUCCESS = 'LOAD_DATA_PAGE_SUCCESS',
  LOAD_DATA_PAGE_FAILURE = 'LOAD_DATA_PAGE_FAILURE',
}

export default ActionPages;
